import { CircleDollarSign } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Loader } from '../../components/ui/Loader.jsx';
import classService from '../../services/classService.js';
import feeService from '../../services/feeService.js';
import { getApiErrorMessage } from '../../services/api.js';

const AdminFeesPage = () => {
  const [fees, setFees] = useState([]); const [students, setStudents] = useState([]); const [form, setForm] = useState({ studentId: '', amount: '', dueDate: '' }); const [state, setState] = useState({ loading: true, saving: false, error: '' });
  const load = async () => { try { const [feeData, studentData] = await Promise.all([feeService.getFees(), classService.getStudents()]); setFees(feeData.records || []); setStudents(studentData); setForm((current) => ({ ...current, studentId: current.studentId || studentData[0]?._id || '' })); } catch (error) { setState((current) => ({ ...current, error: getApiErrorMessage(error) })); } finally { setState((current) => ({ ...current, loading: false })); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); try { setState((current) => ({ ...current, saving: true, error: '' })); await feeService.addFee(form); setForm((current) => ({ ...current, amount: '', dueDate: '' })); toast.success('Fee record created'); await load(); } catch (error) { const message = getApiErrorMessage(error); setState((current) => ({ ...current, error: message })); toast.error(message); } finally { setState((current) => ({ ...current, saving: false })); } };
  const pay = async (id) => { try { await feeService.payFee(id); toast.success('Fee marked as paid'); await load(); } catch (error) { toast.error(getApiErrorMessage(error)); } };
  if (state.loading) return <Loader text="Loading fee records..." fullHeight />;
  if (state.error && !fees.length) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-700">{state.error}</div>;
  return <section className="space-y-6"><div><p className="text-sm font-medium uppercase tracking-[0.16em] text-violet-600">Finance</p><h1 className="mt-1 text-3xl font-semibold text-slate-900">Fees</h1><p className="mt-2 text-slate-600">Create fee records and update payment status.</p></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Due date</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{fees.map((fee) => <tr key={fee._id}><td className="px-4 py-3 font-medium">{fee.student?.name || '—'}</td><td className="px-4 py-3">{fee.amount}</td><td className="px-4 py-3">{new Date(fee.dueDate).toLocaleDateString()}</td><td className="px-4 py-3">{fee.status}</td><td className="px-4 py-3">{fee.status !== 'Paid' && <button type="button" onClick={() => pay(fee._id)} className="text-sm font-medium text-violet-600 hover:text-violet-800">Mark paid</button>}</td></tr>)}{!fees.length && <tr><td colSpan="5" className="px-4 py-10 text-center text-slate-500">No fee records found.</td></tr>}</tbody></table></div><form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><CircleDollarSign className="text-violet-600" size={19} /><h2 className="font-semibold">Add fee</h2></div><div className="mt-5 space-y-4"><select required value={form.studentId} onChange={(event) => setForm({ ...form, studentId: event.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Select student</option>{students.map((student) => <option key={student._id} value={student._id}>{student.name} · {student.studentId}</option>)}</select><input required min="0.01" type="number" step="0.01" placeholder="Amount" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /><input required type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" />{state.error && <p className="text-sm text-rose-600">{state.error}</p>}<button type="submit" disabled={state.saving || !students.length} className="w-full rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{state.saving ? 'Saving...' : 'Create fee record'}</button></div></form></div></section>;
};

export default AdminFeesPage;
